FORMAT: 1A9
HOST: https://api.coderi.com.br

# Coderi API
Exemplo de design de API (Application Programing Interface) projetado pela [Coderi : Inteligência Empresarial](http://coderi.com.br).

Mais detalhes e informações logo a seguir.

> **Contato:** Thiago Pereira Rosa - thiagor@engineer.com

### Links
* http://coderi.com.br
* https://github.com/kamihouse/api-design

### Autenticação
Este seria um bom espaço para descrever as informações de autenticação.

Entretanto para não entrar muito em detalhes e extender o escopo desse projeto as informações de autenticação e autorização serão omitidas.

**Cabeçalho HTTP:**

```http
Authorization: bearer 5262d64b892e8d4341000001
```

::: note
A seguir serão descritos os endpoints que compreendem essa API.
:::


<!-- include(resources/users/users.apib) -->
